/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Claces.Distrito;
import Claces.Tipo_Iglesia;
import DAO.DistritoDAO;
import DAO.IgelsiaDAO;//
import DAO.TipoIglesiaDAO;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author aron
 */
public class Principal extends javax.swing.JFrame {

    DefaultComboBoxModel<Object> comboDistrito = new DefaultComboBoxModel<Object>();
     DefaultComboBoxModel<Object> combotipoIglesia = new DefaultComboBoxModel<Object>();
     DistritoDAO dd= new DistritoDAO();
    
     IgelsiaDAO  id= new IgelsiaDAO();
     TipoIglesiaDAO tpDAO= new TipoIglesiaDAO();
     ArrayList<Distrito> lista1= new ArrayList();
     ArrayList<Tipo_Iglesia> lista2= new ArrayList();
    public Principal() {
        initComponents();
        cargarDistrito();
        cargarTipo_Iglesia();
        setLocationRelativeTo(null);
    }
             final void  cargarDistrito()
    {
        comboDistrito.addElement("seleccionar Distrito");
        cboDistrito.setModel(comboDistrito);
        lista1=dd.ListarDistrito();
        for(int i =0;i<lista1.size();i++)
        {
            comboDistrito.addElement(lista1.get(i).getDistrito());
        }
        cboDistrito.setModel(comboDistrito);
    }
   final void  cargarTipo_Iglesia()
    {
        combotipoIglesia.addElement("seleccionar Tipo  Iglesia");
        cboTipoIglesia.setModel(combotipoIglesia);
        lista2=tpDAO.ListarTipo_Iglesia();
        for(int i =0;i<lista2.size();i++)
        {
            combotipoIglesia.addElement(lista2.get(i).getNom_tipo());
        }
        cboTipoIglesia.setModel(combotipoIglesia);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboDistrito = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboTipoIglesia = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtIglesia = new javax.swing.JTextField();
        txtCuenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Distrito:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        getContentPane().add(cboDistrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 230, -1));

        jLabel2.setText("Tipo Iglesia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        getContentPane().add(cboTipoIglesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 230, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Distrito", "tipo Iglesia", "iglesia", "Cuenta"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 90));
        getContentPane().add(txtIglesia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 200, -1));

        txtCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 130, -1));

        jLabel3.setText("Cuenta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jLabel4.setText("Iglesia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox cboDistrito;
    private javax.swing.JComboBox cboTipoIglesia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCuenta;
    private javax.swing.JTextField txtIglesia;
    // End of variables declaration//GEN-END:variables
}
